[phases.setup]
cmds = [
  "nix-collect-garbage -d",
  "nix-env -if .nixpacks/nixpkgs-dbc4f15b899ac77a8d408d8e0f89fa9c0c5f2b78.nix --ignore-collisions",
  "composer install",
  "yarn install"
]

[phases.build]
cmds = [
  "yarn run build",
  "php artisan migrate --force"
]

[phases.nix]
pkgs = [
  "php",
  "composer",
  "nodejs",
  "yarn",
  "postgresql"
]

[phases.deploy]
cmd = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan serve --host=0.0.0.0 --port=8000"
]
