[phases.setup]
cmds = [
  "composer install",
  "yarn install"
]

[phases.build]
cmds = [
  "yarn run build",
  "php artisan migrate --force"
]

[phases.nix]
pkgs = [
  "php",
  "composer",
  "nodejs",
  "yarn",
  "postgresql"
]

[phases.deploy]
cmd = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan serve --host=0.0.0.0 --port=8000"
]
